export const PERSON_LIST_REQUEST = 'PERSON_LIST_REQUEST'
export const PERSON_LIST_SUCCESS = 'PERSON_LIST_SUCCESS'
export const PERSON_LIST_FAIL = 'PERSON_LIST_FAIL'

export const PERSON_DETAILS_REQUEST = 'PERSON_DETAILS_REQUEST'
export const PERSON_DETAILS_SUCCESS = 'PERSON_DETAILS_SUCCESS'
export const PERSON_DETAILS_FAIL = 'PERSON_DETAILS_FAIL'

export const PERSON_DELETE_REQUEST = 'PERSON_DELETE_REQUEST'
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS'
export const PERSON_DELETE_FAIL = 'PERSON_DELETE_FAIL'

export const PERSON_CREATE_REQUEST = 'PERSON_CREATE_REQUEST'
export const PERSON_CREATE_SUCCESS = 'PERSON_CREATE_SUCCESS'
export const PERSON_CREATE_FAIL = 'PERSON_CREATE_FAIL'
export const PERSON_CREATE_RESET = 'PERSON_CREATE_RESET'
