export const RESEARCH_LIST_REQUEST = 'RESEARCH_LIST_REQUEST'
export const RESEARCH_LIST_SUCCESS = 'RESEARCH_LIST_SUCCESS'
export const RESEARCH_LIST_FAIL = 'RESEARCH_LIST_FAIL'

export const RESEARCH_CREATE_REQUEST = 'RESEARCH_CREATE_REQUEST'
export const RESEARCH_CREATE_SUCCESS = 'RESEARCH_CREATE_SUCCESS'
export const RESEARCH_CREATE_FAIL = 'RESEARCH_CREATE_FAIL'
export const RESEARCH_CREATE_RESET = 'RESEARCH_CREATE_RESET'

export const RESEARCH_DETAILS_REQUEST = 'RESEARCH_DETAILS_REQUEST'
export const RESEARCH_DETAILS_SUCCESS = 'RESEARCH_DETAILS_SUCCESS'
export const RESEARCH_DETAILS_FAIL = 'RESEARCH_DETAILS_FAIL'
