export const RESEARCH_LIST_REQUEST = 'RESEARCH_LIST_REQUEST'
export const RESEARCH_LIST_SUCCESS = 'RESEARCH_LIST_SUCCESS'
export const RESEARCH_LIST_FAIL = 'RESEARCH_LIST_FAIL'

export const RESEARCH_CREATE_REQUEST = 'RESEARCH_CREATE_REQUEST'
export const RESEARCH_CREATE_SUCCESS = 'RESEARCH_CREATE_SUCCESS'
export const RESEARCH_CREATE_FAIL = 'RESEARCH_CREATE_FAIL'
export const RESEARCH_CREATE_RESET = 'RESEARCH_CREATE_RESET'

export const RESEARCH_DETAILS_REQUEST = 'RESEARCH_DETAILS_REQUEST'
export const RESEARCH_DETAILS_SUCCESS = 'RESEARCH_DETAILS_SUCCESS'
export const RESEARCH_DETAILS_FAIL = 'RESEARCH_DETAILS_FAIL'

export const RESEARCH_DELETE_REQUEST = 'RESEARCH_DELETE_REQUEST'
export const RESEARCH_DELETE_SUCCESS = 'RESEARCH_DELETE_SUCCESS'
export const RESEARCH_DELETE_FAIL = 'RESEARCH_DELETE_FAIL'

export const RESEARCH_UPDATE_REQUEST = 'RESEARCH_UPDATE_REQUEST'
export const RESEARCH_UPDATE_SUCCESS = 'RESEARCH_UPDATE_SUCCESS'
export const RESEARCH_UPDATE_FAIL = 'RESEARCH_UPDATE_FAIL'
export const RESEARCH_UPDATE_RESET = 'RESEARCH_UPDATE_RESET'
